# Configure main menu and social menu
[[main]]
identifier = "home"
name = "Home"
url = "/"
[main.params]
icon = "home"
label_en = "Home"
label_zh = "首页"

[[main]]
identifier = "reading"
name = "Reading"
url = "/reading/"
[main.params]
icon = "tag"
label_en = "Reading"
label_zh = "阅读摘记"

[[main]]
identifier = "reflections"
name = "Reflections"
url = "/reflections/"
[main.params]
icon = "search"
label_en = "Reflections"
label_zh = "思考随笔"

[[main]]
identifier = "archives"
name = "Archives"
url = "/archives/"
[main.params]
icon = "archives"
bottom = true
label_en = "Archives"
label_zh = "归档"

[[main]]
identifier = "about"
name = "About"
url = "/about/"
[main.params]
icon = "user"
bottom = true
label_en = "About"
label_zh = "关于"

[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/GoToBoy/blog"

    [social.params]
        icon = "brand-github"
