# Permalinks format of each content section
reading = "/reading/:slugorcontentbasename/"
reflections = "/reflections/:slugorcontentbasename/"
weeks = "/weeks/:slugorcontentbasename/"
page = "/:slug/"
